# GitHub Sponsors and external funding links
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ['https://afdian.com/a/tianma-if']
