import { StyleSheet } from "react-native";
import { MEMO_CONTENT_STYLE } from "@edgeever/shared";
import { MOBILE_UI_METRICS } from "@edgeever/shared/mobile-ui";
import { resolveMobileThemeStyles, type MobileResolvedTheme } from "../lib/mobile-theme";

const DETAIL_CONTENT_HORIZONTAL_PADDING = 16;

const baseWorkspaceStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: "#f8fafc",
    flex: 1,
  },
  viewBody: {
    flex: 1,
    paddingBottom: 0,
  },
  settingsScreen: {
    backgroundColor: "#f8fafc",
    flex: 1,
  },
  settingsHeader: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 56,
    paddingHorizontal: 12,
  },
  settingsBackButton: {
    alignItems: "center",
    borderRadius: 8,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  settingsThemeButton: {
    alignItems: "center",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    height: 36,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  settingsThemeText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "700",
  },
  settingsHeaderTitle: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-start",
  },
  updateDot: {
    backgroundColor: "#10b981",
    borderColor: "#ffffff",
    borderRadius: 5,
    borderWidth: 1,
    height: 9,
    marginLeft: 1,
    width: 9,
  },
  settingsTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "800",
  },
  settingsScrollContent: {
    padding: 16,
    paddingBottom: 96,
  },
  settingsMenu: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 16,
    borderWidth: 1,
    overflow: "hidden",
  },
  settingsMenuRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 64,
    paddingHorizontal: 16,
  },
  settingsMenuRowBorder: {
    borderTopColor: "#f1f5f9",
    borderTopWidth: 1,
  },
  settingsMenuLabel: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 12,
    minWidth: 0,
  },
  settingsMenuIcon: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 8,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  settingsMenuText: {
    color: "#1e293b",
    fontSize: 14,
    fontWeight: "700",
  },
  settingsMenuTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  settingsFeedbackCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  settingsFeedbackDescription: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
  },
  settingsUpdateDescription: {
    color: "#047857",
    fontWeight: "600",
  },
  settingsFeedbackIcon: {
    backgroundColor: "#f1f5f9",
  },
  settingsDetailList: {
    gap: 16,
  },
  accountSummaryCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 16,
  },
    accountSummaryIcon: {
      alignItems: "center",
      backgroundColor: "#ecfdf5",
    borderRadius: 999,
    height: 40,
      justifyContent: "center",
      width: 40,
    },
    accountSummaryContent: {
      flex: 1,
      minWidth: 0,
    },
    accountSummaryHelp: {
      color: "#64748b",
      fontSize: 12,
      lineHeight: 18,
      marginTop: 3,
    },
    accountSummaryTitle: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  accountSummaryName: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
    marginTop: 2,
  },
  settingsGroup: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 12,
    borderWidth: 1,
    overflow: "hidden",
  },
  settingsAiEmbeddedCardFirst: {
    borderRadius: 0,
    borderWidth: 0,
  },
  settingsAiEmbeddedCard: {
    borderBottomWidth: 0,
    borderLeftWidth: 0,
    borderRadius: 0,
    borderRightWidth: 0,
    borderTopColor: "#f1f5f9",
    borderTopWidth: 1,
  },
  settingsGroupHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    padding: 16,
  },
  settingsGroupTitle: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "800",
  },
  settingsContentRow: {
    borderTopColor: "#f1f5f9",
    borderTopWidth: 1,
    gap: 10,
    minHeight: 64,
    padding: 16,
  },
  settingsSelect: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 40,
    paddingHorizontal: 12,
  },
  settingsSelectText: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
  },
  settingsSwitchStart: {
    alignItems: "flex-start",
  },
  settingsRowTitle: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "700",
  },
  settingsRowDescription: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
  },
  settingsLinkDescription: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 16,
  },
  settingsAccordionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingRight: 16,
  },
  settingsAccordionChevron: {
    transform: [{ rotate: "0deg" }],
  },
  settingsAccordionChevronExpanded: {
    transform: [{ rotate: "180deg" }],
  },
  settingsAccordionContent: {
    borderTopColor: "#f1f5f9",
    borderTopWidth: 1,
    gap: 10,
    padding: 16,
  },
  settingsDialogBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.46)",
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  localePickerBackdrop: {
    flex: 1,
  },
  localePickerMenu: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    elevation: 8,
    overflow: "hidden",
    padding: 4,
    position: "absolute",
    shadowColor: "#0f172a",
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 10,
  },
  localePickerOption: {
    alignItems: "center",
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 38,
    paddingHorizontal: 10,
  },
  localePickerOptionActive: {
    backgroundColor: "#ecfdf5",
  },
  localePickerOptionText: {
    color: "#334155",
    flex: 1,
    fontSize: 14,
  },
  localePickerOptionTextActive: {
    color: "#047857",
    fontWeight: "700",
  },
  settingsLinkCopy: {
    flex: 1,
    paddingBottom: 16,
  },
  settingsLogoutButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#e11d48",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 14,
  },
  settingsLogoutCard: {
    backgroundColor: "#fff1f2",
    borderColor: "#fecaca",
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  settingsLogoutText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  iconButtonPlaceholder: {
    height: 38,
    width: 38,
  },
  mobileListHeader: {
    backgroundColor: "#f8fafc",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    paddingBottom: 8,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  mobileSelectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    minHeight: 44,
  },
  mobileSelectionTitle: {
    color: "#0f172a",
    flex: 1,
    fontSize: 17,
    fontWeight: "800",
    paddingHorizontal: 8,
  },
  mobileSelectionClose: {
    alignItems: "center",
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  mobileListTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    minHeight: MOBILE_UI_METRICS.compactControlHeight,
  },
  mobileNotebookTitleButton: {
    alignItems: "center",
    flexDirection: "row",
    flexShrink: 1,
    gap: 4,
    minHeight: MOBILE_UI_METRICS.compactControlHeight,
    paddingRight: 12,
  },
  mobileNotebookTitle: {
    color: "#0f172a",
    flexShrink: 1,
    fontSize: 17,
    fontWeight: "700",
  },
  mobileMoreButton: {
    alignItems: "center",
    borderRadius: MOBILE_UI_METRICS.compactControlHeight / 2,
    height: MOBILE_UI_METRICS.compactControlHeight,
    justifyContent: "center",
    width: MOBILE_UI_METRICS.compactControlHeight,
  },
  mobileSearchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  mobileSearchButton: {
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    borderColor: "transparent",
    borderRadius: MOBILE_UI_METRICS.compactControlHeight / 2,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    height: MOBILE_UI_METRICS.compactControlHeight,
    paddingHorizontal: 12,
  },
  mobileSearchButtonActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  mobileSearchButtonActiveDark: {
    backgroundColor: "rgb(255, 255, 255)",
  },
  mobileSearchInput: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    height: MOBILE_UI_METRICS.compactControlHeight,
    paddingVertical: 0,
  },
  mobileSearchInputActiveDark: {
    color: "rgb(15, 23, 42)",
  },
  mobileSearchClearButton: {
    alignItems: "center",
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  mobileListConstraint: {
    alignItems: "center",
    backgroundColor: "rgb(236, 253, 245)",
    borderColor: "rgb(167, 243, 208)",
    borderLeftColor: "rgb(16, 185, 129)",
    borderLeftWidth: 3,
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    minHeight: 32,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  mobileListConstraintFilter: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderLeftColor: "#e2e8f0",
    borderLeftWidth: 1,
  },
  mobileSearchStatusPill: {
    alignItems: "center",
    backgroundColor: "#059669",
    borderRadius: 999,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mobileSearchStatusPillText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  mobileListConstraintText: {
    color: "#065f46",
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
  },
  mobileListConstraintTextFilter: {
    color: "#64748b",
  },
  mobileListConstraintAction: {
    color: "#065f46",
    fontSize: 12,
    fontWeight: "700",
  },
  mobileListConstraintActionFilter: {
    color: "#475569",
  },
  mobileFilterButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: MOBILE_UI_METRICS.compactControlHeight / 2,
    borderWidth: 1,
    height: MOBILE_UI_METRICS.compactControlHeight,
    justifyContent: "center",
    width: MOBILE_UI_METRICS.compactControlHeight,
  },
  mobileFilterButtonActive: {
    backgroundColor: "#334155",
    borderColor: "#334155",
  },
  searchBox: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 46,
    paddingHorizontal: 12,
  },
  searchInput: {
    color: "#0f172a",
    flex: 1,
    fontSize: 15,
    minHeight: 44,
  },
  layoutToggle: {
    alignSelf: "flex-start",
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    overflow: "hidden",
  },
  layoutToggleButton: {
    alignItems: "center",
    flexDirection: "row",
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  layoutToggleButtonActive: {
    backgroundColor: "#ecfdf5",
  },
  secondaryIconButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  optionPill: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    marginRight: 6,
    minHeight: 32,
    paddingHorizontal: 12,
  },
  optionPillActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  optionPillText: {
    color: "#475569",
    fontSize: 13,
    fontWeight: "700",
  },
  optionPillTextActive: {
    color: "#047857",
  },
  list: {
    paddingBottom: 18,
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  memoList: {
    flex: 1,
  },
  listLoadingFooter: {
    marginVertical: 18,
  },
  emptyList: {
    flexGrow: 1,
    paddingBottom: 22,
  },
  memoListStateWrap: {
    paddingHorizontal: 12,
    paddingTop: 16,
  },
  memoListLoadingCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#a7f3d0",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 34,
  },
  memoListLoadingTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 14,
  },
  memoListLoadingDescription: {
    color: "#64748b",
    fontSize: 13,
    lineHeight: 20,
    marginTop: 7,
    maxWidth: 300,
    textAlign: "center",
  },
  memoSyncBanner: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  memoSyncBannerContent: {
    flex: 1,
  },
  memoSyncBannerTitle: {
    color: "#065f46",
    fontSize: 13,
    fontWeight: "800",
  },
  memoSyncBannerDescription: {
    color: "#047857",
    fontSize: 12,
    marginTop: 2,
  },
  memoSyncProgressTrack: {
    backgroundColor: "#d1fae5",
    borderRadius: 999,
    height: 4,
    marginTop: 10,
    overflow: "hidden",
    width: "100%",
  },
  memoSyncProgressFill: {
    backgroundColor: "#059669",
    borderRadius: 999,
    height: "100%",
  },
  memoSyncErrorBanner: {
    alignItems: "center",
    backgroundColor: "#fffbeb",
    borderColor: "#fcd34d",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginBottom: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  memoSyncErrorBannerTitle: {
    color: "#451a03",
    fontSize: 13,
    fontWeight: "800",
  },
  memoSyncErrorBannerDescription: {
    color: "#92400e",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
  },
  memoSyncErrorRetryButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  memoListErrorCard: {
    alignItems: "center",
    backgroundColor: "#fffbeb",
    borderColor: "#fcd34d",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 34,
  },
  memoListErrorTitle: {
    color: "#451a03",
    fontSize: 14,
    fontWeight: "800",
  },
  memoListErrorDescription: {
    color: "#92400e",
    fontSize: 12,
    lineHeight: 20,
    marginTop: 8,
    maxWidth: 300,
    textAlign: "center",
  },
  memoListRetryButton: {
    alignItems: "center",
    backgroundColor: "#fef3c7",
    borderRadius: 8,
    flexDirection: "row",
    gap: 7,
    marginTop: 16,
    minHeight: 36,
    paddingHorizontal: 12,
  },
  memoListRetryText: {
    color: "#92400e",
    fontSize: 13,
    fontWeight: "800",
  },
  memoListEmptyCard: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    marginHorizontal: 12,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 34,
  },
  memoCard: {
    alignItems: "stretch",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    marginBottom: 12,
    minHeight: 132,
    overflow: "hidden",
  },
  memoCardCompact: {
    marginBottom: 10,
    minHeight: 84,
  },
  memoCardSelected: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
  },
  memoCardContent: {
    flex: 1,
    minWidth: 0,
    padding: 15,
  },
  memoCardContentCompact: {
    padding: 12,
  },
  memoCardContentWithSelection: {
    paddingLeft: 12,
  },
  memoSelectionButton: {
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    width: 44,
  },
  memoCardTop: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
  },
  selectionIndicator: {
    alignItems: "center",
    borderColor: "#cbd5e1",
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  selectionIndicatorActive: {
    backgroundColor: "#0f172a",
    borderColor: "#0f172a",
  },
  memoTitle: {
    color: "#0f172a",
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  memoPinnedStar: {
    color: "#64748b",
    fontSize: 16,
    lineHeight: 16,
    width: 16,
  },
  memoExcerpt: {
    color: "#475569",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 6,
    minHeight: 38,
  },
  memoMeta: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
  },
  memoMetaCompact: {
    marginTop: 6,
  },
  memoDate: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "400",
  },
  tag: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 3,
    borderWidth: 1,
    color: "#047857",
    fontSize: 11,
    fontWeight: "600",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  centerState: {
    alignItems: "center",
    flex: 1,
    gap: 8,
    justifyContent: "center",
    padding: 24,
  },
  errorText: {
    color: "#dc2626",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 20,
  },
  emptyTitle: {
    color: "#334155",
    fontSize: 16,
    fontWeight: "800",
  },
  mutedText: {
    color: "#64748b",
    fontSize: 13,
    textAlign: "center",
  },
  emptyActionButton: {
    alignItems: "center",
    backgroundColor: "#0f172a",
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    minHeight: 38,
    paddingHorizontal: 14,
  },
  emptyActionButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "800",
  },
  emptyActionRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
    marginTop: 8,
  },
  emptyActionSecondaryButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 38,
    paddingHorizontal: 14,
  },
  emptyActionSecondaryButtonText: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  createMemoTemplateButton: {
    alignItems: "center",
    borderColor: "#e2e8f0",
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  createMemoTemplateButtonText: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "700",
  },
  templatePickerSheet: {
    maxHeight: "84%",
  },
  /** Absolute fill when nested inside CreateMemoModal (avoid second RN Modal). */
  templatePickerOverlayRoot: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 40,
  },
  templatePickerLoading: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  templatePickerHint: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  templatePickerErrorBlock: {
    gap: 8,
    paddingBottom: 4,
  },
  templatePickerErrorDetail: {
    color: "#b91c1c",
    fontSize: 11,
    lineHeight: 16,
    paddingHorizontal: 8,
  },
  templatePickerRetryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    marginHorizontal: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  templatePickerRetryText: {
    color: "#0f172a",
    fontSize: 12,
    fontWeight: "700",
  },
  templateRow: {
    alignItems: "flex-start",
    borderRadius: 12,
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  templateRowIcon: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 10,
    height: 32,
    justifyContent: "center",
    marginTop: 1,
    width: 32,
  },
  templateRowText: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  templateRowTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  templateRowTitle: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  templateRowDescription: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
  },
  templateChoiceRow: {
    alignItems: "center",
    borderRadius: 12,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 10,
    paddingVertical: 14,
  },
  templateChoiceRowDisabled: {
    opacity: 0.45,
  },
  templateChoiceIcon: {
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  templateChoiceText: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  templateChoiceTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "700",
  },
  templateChoiceDescription: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 17,
  },
  panelRow: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 6,
    padding: 14,
  },
  systemInfoRows: {
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  systemInfoSection: {
    gap: 9,
    paddingHorizontal: 12,
    paddingTop: 14,
  },
  systemInfoSectionHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  systemInfoSectionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  systemInfoSectionTitle: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  systemInfoSectionDescription: {
    color: "#64748b",
    fontSize: 11,
    lineHeight: 16,
  },
  systemInfoRow: {
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
  },
  systemInfoRowLast: {
    borderBottomWidth: 0,
  },
  systemInfoCell: {
    flex: 1,
    gap: 3,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 9,
  },
  systemInfoCellDivider: {
    borderRightColor: "#e2e8f0",
    borderRightWidth: 1,
  },
  systemInfoListValue: {
    color: "#0f172a",
    fontFamily: "monospace",
    fontSize: 12,
    fontWeight: "700",
  },
  panelLinkRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  panelLinkText: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  panelLabel: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  panelValue: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "700",
  },
  preferenceStack: {
    gap: 12,
  },
  preferenceText: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  modalSafeArea: {
    backgroundColor: "#f8fafc",
    flex: 1,
  },
  createMemoSafeArea: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  createMemoHeader: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderBottomColor: "#f1f5f9",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    minHeight: 52,
    paddingBottom: 8,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  createMemoBackButton: {
    alignItems: "center",
    borderRadius: 999,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  createMemoHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  createMemoStatus: {
    backgroundColor: "#f1f5f9",
    borderRadius: 999,
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  createMemoStatusActive: {
    backgroundColor: "#ecfdf5",
    color: "#047857",
  },
  createMemoDoneButton: {
    alignItems: "center",
    backgroundColor: "#020617",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 36,
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  createMemoDoneButtonDisabled: {
    backgroundColor: "#e2e8f0",
  },
  createMemoDoneText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  createMemoDoneTextDisabled: {
    color: "#64748b",
  },
  createMemoMain: {
    flex: 1,
    paddingBottom: 8,
    paddingHorizontal: 12,
    paddingTop: 14,
  },
  createMemoTitleInput: {
    color: "#0f172a",
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
    minHeight: 42,
    padding: 0,
  },
  createMemoMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 40,
  },
  createMemoNotebookButton: {
    alignItems: "center",
    flexDirection: "row",
    flexShrink: 1,
    gap: 3,
    maxWidth: "46%",
    minHeight: 30,
    paddingRight: 5,
  },
  createMemoNotebookText: {
    color: "#64748b",
    flexShrink: 1,
    fontSize: 15,
    fontWeight: "700",
  },
  createMemoTagsInput: {
    color: "#64748b",
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    minWidth: 0,
    padding: 0,
  },
  createMemoTagsButton: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 36,
    minWidth: 0,
  },
  createMemoTagsPlaceholder: {
    color: "#94a3b8",
  },
  smartTagButton: {
    alignItems: "center",
    borderRadius: 8,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  smartTagButtonSuccess: {
    backgroundColor: "#ecfdf5",
  },
  createMemoToolButton: {
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 36,
  },
  createMemoToolButtonPressed: {
    backgroundColor: "#ecfdf5",
    borderColor: "#bbf7d0",
  },
  createMemoEditorFrame: {
    borderColor: "#e2e8f0",
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    marginHorizontal: -4,
    marginTop: 4,
    overflow: "hidden",
  },
  createMemoEditor: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  richEditorSafeArea: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  richEditorKeyboardAvoiding: {
    flex: 1,
  },
  richEditorHeaderStatus: {
    maxWidth: 76,
  },
  richEditorContainer: {
    backgroundColor: "#ffffff",
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 14,
  },
  richEditorStatusError: {
    backgroundColor: "#fef2f2",
    color: "#b91c1c",
  },
  richEditorFrame: {
    flex: 1,
    marginHorizontal: -12,
  },
  richStandaloneMetaRow: {
    minHeight: 30,
  },
  richStandaloneTagsInput: {
    minHeight: 30,
  },
  richEditorSearchActions: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  richEditorLoading: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    bottom: 0,
    gap: 10,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 2,
  },
  richEditorLoadingTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  richEditorWebView: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  richEditorInlineError: {
    backgroundColor: "#fef2f2",
    color: "#b91c1c",
    fontSize: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  richEditorDraftNotice: {
    backgroundColor: "#fffbeb",
    color: "#92400e",
    fontSize: 12,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  richEditorPerf: {
    backgroundColor: "#f8fafc",
    color: "#64748b",
    fontSize: 10,
    paddingHorizontal: 14,
    paddingVertical: 4,
    textAlign: "right",
  },
  managementHeader: {
    alignItems: "center",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 64,
    paddingHorizontal: 14,
  },
  managementBackButton: {
    alignItems: "center",
    borderRadius: 8,
    height: 36,
    justifyContent: "center",
    marginRight: 10,
    width: 36,
  },
  managementHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  managementTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  managementTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "800",
  },
  managementSubtitle: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "600",
    marginTop: 2,
  },
  modalHeader: {
    alignItems: "center",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 14,
  },
  modalTitle: {
    color: "#0f172a",
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    marginHorizontal: 12,
    textAlign: "center",
  },
  actionSheetBackdrop: {
    backgroundColor: "rgba(15, 23, 42, 0.34)",
    flex: 1,
    justifyContent: "flex-end",
  },
  actionSheet: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    gap: 8,
    paddingBottom: 28,
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  listActionSheet: {
    backgroundColor: "#ffffff",
    borderRadius: MOBILE_UI_METRICS.floatingSheetCornerRadius,
    marginHorizontal: 12,
    maxHeight: "82%",
    overflow: "hidden",
    paddingBottom: 8,
    paddingTop: 8,
  },
  selectionMoreSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 10,
    gap: 0,
    marginHorizontal: 8,
    overflow: "hidden",
    paddingBottom: 8,
    paddingTop: 8,
  },
  moveSelectionSheet: {
    maxHeight: "76%",
  },
  moveSelectionSearch: {
    borderBottomColor: "#f1f5f9",
    borderBottomWidth: 1,
    padding: 12,
  },
  moveSelectionList: {
    gap: 8,
    padding: 8,
  },
  listActionSheetHeader: {
    alignItems: "center",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  listActionSheetHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  sheetCloseButton: {
    alignItems: "center",
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  listActionSheetScroll: {
    flexShrink: 1,
  },
  listActionSheetContent: {
    padding: 8,
  },
  actionSheetSubtitle: {
    color: "#64748b",
    fontSize: 12,
    marginTop: 2,
  },
  listActionDivider: {
    backgroundColor: "#f1f5f9",
    height: 1,
    marginVertical: 8,
  },
  notebookPickerSheet: {
    maxHeight: "82%",
    paddingBottom: 8,
    paddingHorizontal: 0,
  },
  notebookPickerHeader: {
    alignItems: "center",
    borderBottomColor: "#e2e8f0",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 56,
    paddingHorizontal: 16,
  },
  notebookPickerHeaderText: {
    flex: 1,
    gap: 2,
  },
  notebookPickerCloseButton: {
    alignItems: "center",
    borderRadius: 6,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  notebookPickerSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 32,
    paddingHorizontal: 12,
  },
  notebookPickerToggleAll: {
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  notebookPickerToggleAllText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  notebookPickerScroll: {
    flexShrink: 1,
  },
  notebookPickerContent: {
    padding: 8,
  },
  notebookPickerSearchBox: {
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    borderRadius: 6,
    flexDirection: "row",
    gap: 8,
    height: 36,
    marginBottom: 8,
    paddingHorizontal: 12,
  },
  notebookPickerSearchInput: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    height: 36,
    paddingVertical: 0,
  },
  notebookPickerRow: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 6,
    flexDirection: "row",
    gap: 8,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  notebookPickerAllRow: {
    marginBottom: 4,
  },
  notebookPickerRowActive: {
    backgroundColor: "#f1f5f9",
  },
  tagPickerSelectedList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  tagPickerChip: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    flexDirection: "row",
    gap: 4,
    minHeight: 32,
    paddingHorizontal: 11,
  },
  tagPickerChipText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "700",
  },
  tagPickerCreateText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "800",
  },
  tagPickerLoading: {
    paddingVertical: 28,
  },
  tagPickerCheckbox: {
    alignItems: "center",
    borderColor: "#cbd5e1",
    borderRadius: 5,
    borderWidth: 1,
    height: 22,
    justifyContent: "center",
    width: 22,
  },
  tagPickerCheckboxSelected: {
    backgroundColor: "#16a06e",
    borderColor: "#16a06e",
  },
  tagPickerRowText: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
  },
  actionSheetHandle: {
    alignSelf: "center",
    backgroundColor: "#cbd5e1",
    borderRadius: 999,
    height: 4,
    marginBottom: 8,
    width: 42,
  },
  actionSheetTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "800",
    paddingBottom: 4,
  },
  actionSheetSectionTitle: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "600",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  actionSheetItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 7,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  actionSheetItemCompact: {
    minHeight: 44,
  },
  actionSheetItemText: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "800",
  },
  actionSheetItemTextCompact: {
    fontWeight: "500",
  },
  actionSheetItemTextDanger: {
    color: "#b91c1c",
  },
  sheetOptionRow: {
    alignItems: "center",
    borderRadius: 7,
    flexDirection: "row",
    gap: 10,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  sheetOptionRowActive: {
    backgroundColor: "rgb(236, 253, 245)",
  },
  sheetOptionIcon: {
    alignItems: "center",
    justifyContent: "center",
    width: 20,
  },
  sheetOptionLabel: {
    color: "#0f172a",
    flex: 1,
    fontSize: 14,
    fontWeight: "500",
  },
  sheetOptionLabelActive: {
    color: "rgb(4, 120, 87)",
  },
  sheetOptionCheck: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 9,
    height: 18,
    justifyContent: "center",
    width: 18,
  },
  sheetOptionCheckHidden: {
    opacity: 0,
  },
  detailContent: {
    paddingBottom: 112,
    paddingHorizontal: DETAIL_CONTENT_HORIZONTAL_PADDING,
    paddingTop: 16,
  },
  detailTitle: {
    color: "#0f172a",
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 30,
  },
  detailHeader: {
    alignItems: "center",
    borderBottomColor: "#f1f5f9",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    paddingHorizontal: 12,
  },
  detailHeaderButton: {
    alignItems: "center",
    borderRadius: 6,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  detailHeaderActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 2,
  },
  detailHeaderIconButton: {
    alignItems: "center",
    borderRadius: 6,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  detailSyncStatus: {
    backgroundColor: "#f1f5f9",
    borderRadius: 999,
    color: "#64748b",
    fontSize: 11,
    fontWeight: "500",
    maxWidth: 88,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  detailSyncStatusConflict: {
    backgroundColor: "#fff7ed",
    color: "#c2410c",
    fontWeight: "700",
  },
  detailSyncStatusError: {
    backgroundColor: "#fef2f2",
    color: "#b91c1c",
    fontWeight: "700",
  },
  detailSyncStatusPending: {
    backgroundColor: "#eff6ff",
    color: "#1d4ed8",
    fontWeight: "600",
  },
  syncErrorBanner: {
    backgroundColor: "#fef2f2",
    borderBottomColor: "#fecaca",
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  syncErrorBannerText: {
    color: "#991b1b",
    fontSize: 12,
    lineHeight: 18,
  },
  syncErrorBannerPrimaryButton: {
    backgroundColor: "#b91c1c",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  syncErrorBannerSecondaryButton: {
    backgroundColor: "#fff",
    borderColor: "#fecaca",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  syncErrorBannerSecondaryButtonText: {
    color: "#991b1b",
    fontSize: 12,
    fontWeight: "600",
  },
  syncPendingBanner: {
    backgroundColor: "#eff6ff",
    borderBottomColor: "#bfdbfe",
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  syncPendingBannerText: {
    color: "#1e3a8a",
    fontSize: 12,
    lineHeight: 18,
  },
  syncPendingBannerPrimaryButton: {
    backgroundColor: "#1d4ed8",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  conflictBanner: {
    backgroundColor: "#fff1f2",
    borderBottomColor: "#fecdd3",
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  conflictBannerText: {
    color: "#9f1239",
    fontSize: 12,
    lineHeight: 18,
  },
  conflictBannerActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  conflictBannerPrimaryButton: {
    backgroundColor: "#be123c",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  conflictBannerPrimaryButtonText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  conflictBannerSecondaryButton: {
    backgroundColor: "#fff",
    borderColor: "#fecdd3",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  conflictBannerSecondaryButtonText: {
    color: "#9f1239",
    fontSize: 12,
    fontWeight: "600",
  },
  detailMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  detailNotebookButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    height: 32,
    maxWidth: "46%",
    paddingHorizontal: 8,
  },
  detailNotebookName: {
    color: "#64748b",
    flexShrink: 1,
    fontSize: 14,
  },
  detailTagsGroup: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 8,
    height: 32,
    paddingHorizontal: 8,
  },
  detailTagsInline: {
    color: "#64748b",
    flex: 1,
    fontSize: 14,
  },
  detailTagsPlaceholder: {
    color: "#94a3b8",
  },
  detailTimestamps: {
    color: "#94a3b8",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  detailDivider: {
    backgroundColor: "#e2e8f0",
    height: 1,
    marginHorizontal: -16,
    marginTop: 16,
    marginBottom: 18,
  },
  detailEditFab: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 24,
    elevation: 6,
    height: 48,
    justifyContent: "center",
    position: "absolute",
    right: 16,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    width: 48,
  },
  detailMarkdown: {
    color: "#1f2937",
    fontSize: MEMO_CONTENT_STYLE.body.fontSize,
    lineHeight: MEMO_CONTENT_STYLE.body.lineHeight,
    marginTop: 20,
  },
  noteSearchPanel: {
    backgroundColor: "#f8fafc",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    marginTop: 14,
    padding: 10,
  },
  noteSearchCount: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "800",
  },
  noteSearchCountEmpty: {
    color: "#b91c1c",
  },
  noteSearchHighlight: {
    backgroundColor: "#fef3c7",
    color: "#78350f",
  },
  noteSearchHighlightActive: {
    backgroundColor: "#fde68a",
    color: "#0f172a",
    fontWeight: "800",
  },
  actionButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  actionButtonDanger: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
  },
  actionButtonText: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  actionButtonTextDanger: {
    color: "#b91c1c",
  },
  parentSelectList: {
    flexGrow: 0,
  },
  notebookPicker: {
    gap: 10,
  },
  centerInline: {
    alignItems: "center",
    padding: 18,
  },
  emptyInlinePanel: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 8,
    padding: 22,
  },
  guideHero: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  promptCard: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  promptCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  moveNotebookRow: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 58,
    padding: 12,
  },
  moveNotebookRowActive: {
    borderColor: "#0f172a",
  },
  moveNotebookRowCompact: {
    borderWidth: 0,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  moveNotebookRowCompactActive: {
    backgroundColor: "#ecfdf5",
  },
  moveNotebookTextCompactActive: {
    color: "#047857",
  },
  moveNotebookText: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  moveNotebookSelectArea: {
    flex: 1,
    gap: 4,
    justifyContent: "center",
    minHeight: 34,
    minWidth: 0,
  },
  notebookTreeToggle: {
    alignItems: "center",
    borderRadius: 8,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  notebookTreeTogglePlaceholder: {
    alignItems: "center",
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  notebookTreeRows: {
    gap: 10,
  },
  notebookTreeRowsCompact: {
    gap: 0,
  },
  editorForm: {
    gap: 12,
    padding: 18,
    paddingBottom: 48,
  },
  revisionHistoryContent: {
    gap: 12,
    padding: 16,
    paddingBottom: 48,
  },
  revisionSummaryRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  revisionSummaryText: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  revisionChangeBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#fffbeb",
    borderColor: "#fde68a",
    borderRadius: 999,
    borderWidth: 1,
    color: "#92400e",
    fontSize: 11,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  revisionTimelineLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  revisionTimeline: {
    gap: 7,
  },
  revisionTimelineState: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#cbd5e1",
    borderRadius: 8,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 32,
  },
  revisionTimelineError: {
    color: "#64748b",
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
  },
  revisionPill: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 68,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  revisionPillActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  revisionPillTitle: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "800",
  },
  revisionPillTitleActive: {
    color: "#047857",
  },
  revisionPillMeta: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
  },
  revisionPreviewCard: {
    backgroundColor: "#ffffff",
    borderColor: "#e2e8f0",
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
  },
  revisionPreviewText: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 20,
  },
  label: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  bottomNav: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderTopColor: "#e2e8f0",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 36,
  },
  bottomCreateButton: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderColor: "#ffffff",
    borderRadius: MOBILE_UI_METRICS.floatingCreateButtonSize / 2,
    borderWidth: 4,
    height: MOBILE_UI_METRICS.floatingCreateButtonSize,
    justifyContent: "center",
    marginTop: -MOBILE_UI_METRICS.floatingCreateButtonLift,
    shadowColor: "#10b981",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.28,
    shadowRadius: 18,
    width: MOBILE_UI_METRICS.floatingCreateButtonSize,
  },
  bottomCreateButtonDisabled: {
    backgroundColor: "#cbd5e1",
    shadowOpacity: 0,
  },
  selectionBar: {
    backgroundColor: "#ffffff",
    borderTopColor: "#e2e8f0",
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    paddingHorizontal: 32,
    paddingTop: 4,
    position: "absolute",
    right: 0,
  },
  selectionActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  selectionAction: {
    alignItems: "center",
    flex: 1,
    gap: 4,
    justifyContent: "center",
    minHeight: 56,
  },
  selectionActionText: {
    color: "#0f172a",
    fontSize: 11,
    fontWeight: "800",
  },
  selectionActionTextDanger: {
    color: "#b91c1c",
  },
  bottomNavItem: {
    alignItems: "center",
    gap: 4,
    minHeight: MOBILE_UI_METRICS.minimumTouchTarget,
    minWidth: 58,
  },
  bottomNavIcon: {
    position: "relative",
  },
  bottomNavBadge: {
    backgroundColor: "#10b981",
    borderColor: "#ffffff",
    borderRadius: 5,
    borderWidth: 1,
    height: 9,
    position: "absolute",
    right: -5,
    top: -3,
    width: 9,
  },
  bottomNavText: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "700",
  },
  bottomNavTextActive: {
    color: "#0f172a",
  },
  previewBackdrop: {
    alignItems: "center",
    backgroundColor: "#000000",
    flex: 1,
    justifyContent: "center",
  },
  shareImportBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.42)",
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  shareImportCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 18,
    gap: 10,
    maxWidth: 340,
    paddingHorizontal: 28,
    paddingVertical: 26,
    width: "100%",
  },
  shareImportTitle: {
    color: "#0f172a",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 4,
  },
  shareImportDescription: {
    color: "#64748b",
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
});

export let styles = baseWorkspaceStyles;
let workspaceStylesTheme: MobileResolvedTheme = "light";

export const refreshWorkspaceThemeStyles = (theme: MobileResolvedTheme) => {
  if (workspaceStylesTheme === theme) {
    return;
  }
  styles = resolveMobileThemeStyles(baseWorkspaceStyles, theme);
  workspaceStylesTheme = theme;
};
