const menuCopy = {
  en: {
    about: "About EdgeEver",
    backupNow: "Backup now",
    close: "Close Window",
    copy: "Copy",
    cut: "Cut",
    edit: "Edit",
    file: "File",
    focusSearch: "Focus Search",
    front: "Bring All to Front",
    hide: "Hide EdgeEver",
    minimize: "Minimize",
    newMemo: "New Note",
    newNotebook: "New Notebook",
    paste: "Paste",
    quit: "Quit EdgeEver",
    resetZoom: "Reset Zoom",
    restartToUpdate: "Restart to update",
    selectAll: "Select All",
    show: "Show EdgeEver",
    syncNow: "Sync now",
    toggleFocusMode: "Toggle Focus Mode",
    toggleFullScreen: "Toggle Full Screen",
    undo: "Undo",
    redo: "Redo",
    view: "View",
    window: "Window",
    zoom: "Zoom",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
  },
  zh: {
    about: "关于 EdgeEver",
    backupNow: "立即备份",
    close: "关闭窗口",
    copy: "复制",
    cut: "剪切",
    edit: "编辑",
    file: "文件",
    focusSearch: "定位到搜索",
    front: "全部置于顶层",
    hide: "隐藏 EdgeEver",
    minimize: "最小化",
    newMemo: "新建笔记",
    newNotebook: "新建笔记本",
    paste: "粘贴",
    quit: "退出 EdgeEver",
    resetZoom: "重置缩放",
    restartToUpdate: "重启以更新",
    selectAll: "全选",
    show: "显示 EdgeEver",
    syncNow: "立即同步",
    toggleFocusMode: "切换专注模式",
    toggleFullScreen: "切换全屏",
    undo: "撤销",
    redo: "重做",
    view: "视图",
    window: "窗口",
    zoom: "缩放窗口",
    zoomIn: "放大",
    zoomOut: "缩小",
  },
};

export const desktopMenuCopy = (locale) => (
  typeof locale === "string" && locale.toLowerCase().startsWith("zh")
    ? menuCopy.zh
    : menuCopy.en
);
